const data = [
  {
    id: 1,
    img: "./img/1Vanilla.jpeg",
    nameItem: "Vela Vanilla",
    description: "Aroma romântico, sedutor, de perfume marcante e ao mesmo tempo moderno, acender esta vela promove a sensação de aconchego.",
    value: 45.50,
    addCart: "Adicionar ao Carrinho",
    tag: ["Velas Aromáticas"],
  },

  {
    id: 2,
    img: "./img/2Citrus.jpeg",
    nameItem: "Vela Citrus",
    description:"Um mix perfeito de combinação entre o aroma cítrico com um toque frutado que cria a sensacão de clareza e limpeza no ambiente quando esta vela é acendida.",
    value: 45,
    addCart: "Adicionar ao carrinho",
    tag: ["Velas Aromáticas"],
  },
  {
    id: 3,
    img: "./img/3Menta.jpeg",
    nameItem: "Vela Menta",
    description: "De aroma extremamente agradável, esta vela possui propriedades relaxantes e também, proporciona uma respiração descongestionada.",
    value: 49,
    addCart: "Adicionar ao carrinho",
    tag: ["Velas Aromáticas"],
  },
  {
    id: 4,
    img: "./img/4Canela.jpeg",
    nameItem: "Vela Aromática Maçã e Canela",
    description: "Já imaginou ter o cheirinho de uma torta de maçã recém saída do forno em sua casa? Essa é a sensação ao acender a vela de Maçã e Canela.",
    value: 49,
    addCart: "Adicionar ao carrinho",
    tag: ["Velas Aromáticas"],
  },
  {
    id: 5,
    img: "./img/5Rosas.jpeg",
    nameItem: "Vela Rosas",
    description: "Um dos mais complexos da perfumaria, o aroma de rosas proporciona um aroma que ao mesmo tempo é frutado, profundo e aveludado.",
    value: 45.50,
    addCart: "Adicionar ao carrinho",
    tag: ["Velas Aromáticas"],
  },
  {
    id: 6,
    img: "./img/6Lavanda.jpeg",
    nameItem: "Vela Lavanda",
    description: "Sinta-se acolhido pelo aroma suave da Lavanda, ao acender esta vela que promove uma atmosfera relaxante, confortável e tranquila",
    value: 49,
    addCart: "Adicionar ao carrinho",
    tag: ["Velas Aromáticas"],
  },
  {
    id: 7 ,
    img: "./img/Acessório1.jpeg",
    nameItem: "Suporte Farol",
    description: "Suporte decorativo para velas",
    value: 150 ,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: 8 ,
    img: "./img/Acessório2.jpeg",
    nameItem: "Lanterna Bambu e Vidro",
    description: "Suporte decorativo para velas",
    value: 179,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: 9 ,
    img: "./img/Acessório3.jpeg",
    nameItem: "Porta Vela Bambu",
    description: "Suporte decorativo para velas",
    value: 79,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: 10 ,
    img: "./img/Acessório4.jpeg",
    nameItem: "Suporte lanterna vidro",
    description: "Suporte decorativo para velas",
    value: 189,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: 11 ,
    img: "./img/Acessório5.jpeg",
    nameItem: "Farol vidro e metal",
    description: "Suporte decorativo para velas",
    value: 219,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: 12 ,
    img: "./img/Acessório6.jpeg",
    nameItem: "Potiche Vidro",
    description: "Suporte decorativo para velas",
    value: 79 ,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: 13 ,
    img: "./img/Acessório7.jpeg",
    nameItem: "Difusor para óleos",
    description: "Suporte decorativo para velas",
    value: 129,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: 14 ,
    img: "./img/DifusorLavanda.jpeg",
    nameItem: "Difusor Lavanda",
    description: "Difusor para ambientes, acompanha refil, suporte e varetas de bambu",
    value: 139,
    addCart: "Adicionar ao carrinho",
    tag: ["Difusores"],
  },
  {
    id: 15 ,
    img: "./img/DifusorMacaCanela.jpeg",
    nameItem: "Difusor Maçã e Canela",
    description: "Difusor para ambientes, acompanha refil, suporte e varetas de bambu",
    value: 139,
    addCart: "Adicionar ao carrinho",
    tag: ["Difusores"],
  },
  {
    id: 16 ,
    img: "./img/DifusorPeonias.jpeg",
    nameItem: "Difusor Peônias",
    description: "Difusor para ambientes, acompanha refil, suporte e varetas de bambu",
    value: 139,
    addCart: "Adicionar ao carrinho",
    tag: ["Difusores"],
  },
  {
    id: 17 ,
    img: "./img/DifusorRosas.jpeg",
    nameItem: "Difusor Rosas",
    description: "Difusor para ambientes, acompanha refil, suporte e varetas de bambu",
    value: 139,
    addCart: "Adicionar ao carrinho",
    tag: ["Difusores"],
  },
  {
    id: 17,
    img: "./img/DifusorVanilla.jpeg",
    nameItem: "Difusor Vanilla",
    description: "Difusor para ambientes, acompanha refil, suporte e varetas de bambu",
    value: 139,
    addCart: "Adicionar ao carrinho",
    tag: ["Difusores"],
  },
];
