const data = [
  {
    id: 1,
    img: "../img/1Vanilla.jpeg",
    nameItem: "Vela Vanilla",
    description: "Vela aromática de baunilha",
    value: 45,
    addCart: "Adicionar ao Carrinho",
    tag: ["Velas Aromáticas"],
  },

  {
    id: 2,
    img: "../img/2Citrus.jpeg",
    nameItem: "Vela Citrus",
    description:"Vela aromática de citrus",
    value: 45,
    addCart: "Adicionar ao carrinho",
    tag: ["Velas Aromáticas"],
  },
  {
    id: 3,
    img: "../img/3Menta.jpeg",
    nameItem: "Vela Menta",
    description: "Vela aromática de menta",
    value: 45,
    addCart: "Adicionar ao carrinho",
    tag: ["Velas Aromáticas"],
  },
  {
    id: 4,
    img: "../img/4Canela.jpeg",
    nameItem: "Vela Canela",
    description: "Vela aromática de canela",
    value: 45,
    addCart: "Adicionar ao carrinho",
    tag: ["Velas Aromáticas"],
  },
  {
    id: 5,
    img: "../img/5Rosas.jpeg",
    nameItem: "Vela Rosas",
    description: "Vela aromática de rosas",
    value: 45,
    addCart: "Adicionar ao carrinho",
    tag: ["Velas Aromáticas"],
  },
  {
    id: 6,
    img: "../img/6Lavanda.jpeg",
    nameItem: "Vela Lavanda",
    description: "Vela aromática de lavanda",
    value: 45,
    addCart: "Adicionar ao carrinho",
    tag: ["Velas Aromáticas"],
  },
];
